version: '2'

services:
  redis:
    image: 726902207197.dkr.ecr.us-east-1.amazonaws.com/rmhub-redis:latest

  scheduler:
    image: 726902207197.dkr.ecr.us-east-1.amazonaws.com/rmhub-app:latest
    env_file: docker-compose.env
    command: bash bin/start_scheduler.sh
    links:
      - redis
    depends_on:
      - redis

  worker:
    image: 726902207197.dkr.ecr.us-east-1.amazonaws.com/rmhub-app:latest
    env_file: docker-compose.env
    command: bash bin/start_worker.sh
    links:
      - redis
    depends_on:
      - redis

  web:
    image: 726902207197.dkr.ecr.us-east-1.amazonaws.com/rmhub-web:latest
    env_file: docker-compose.env
    command: bash bin/start_web.sh
    ports:
      - 80:8000
    links:
      - redis
    depends_on:
      - redis
