version: '2.1'

services:
  redis:
    build:
      context: ./
      dockerfile: Dockerfile.redis
    image: rmhub-redis
    ports:
     - 6379:6379

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: rmhub-app
    env_file: docker-compose.env
    command: bash bin/start_scheduler.sh
    links:
      - redis
    depends_on:
      - redis

  worker:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: rmhub-app
    env_file: docker-compose.env
    command: bash bin/start_worker.sh
    links:
      - redis
    depends_on:
      - redis

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    image: rmhub-web
    env_file: docker-compose.env
    command: bash bin/start_web.sh
    ports:
      - 8000:8000
    links:
      - redis
    depends_on:
      - redis