version: '2.1'

services:
  redis:
    image: redismodules.com-redis
    ports:
     - 6379:6379

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: redismodules.com-app
    env_file: docker-compose.env
    command: bash start_scheduler.sh
    links:
      - redis
    depends_on:
      - redis

  worker:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: redismodules.com-app
    env_file: docker-compose.env
    command: bash start_worker.sh
    links:
      - redis
    depends_on:
      - redis

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    image: redismodules.com-web
    env_file: docker-compose.env
    command: bash start_web.sh
    ports:
      - 80:5000
    links:
      - redis
    depends_on:
      - redis